# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  codeblooded
author: Ben Reed
email: benvreed@acm.org
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Student, Software Engineer, Apple enthusiast, Rubyist,
  Cocoahead, upcoming Gopher. Overcomer. Most Important: Totally
  transformed by Jesus Christ!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codeblooded.me" # the base hostname & protocol for your site
twitter_username:  benvreed
github_username:   codeblooded
quora_username:    benvreed
linkedin_username: codeblooded
facebook_username: benvreed
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
